[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Vahid Saadat", email = "vst121@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.142.2",
    "pydantic-settings>=2.15.0",
    "uvicorn[standard]>=0.54.0",
]

[project.scripts]
backend = "backend:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "ruff>=0.16.10",
]
