"""add traffic light state to intersections

Revision ID: 7db9af1d5bc6
Revises: 8fd65443ee2a
Create Date: 2026-10-07 20:24:53.961445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7db9af1d5bc6'
down_revision: Union[str, Sequence[str], None] = '8fd65443ee2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'correlation_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('intersections', 'traffic_light',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('roads', 'geometry',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roads', 'geometry',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('intersections', 'traffic_light',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('events', 'correlation_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
