"""add road geometry

Revision ID: 8fd65443ee2a
Revises: 783770652471
Create Date: 2026-10-06 13:53:07.125580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fd65443ee2a'
down_revision: Union[str, Sequence[str], None] = '783770652471'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'correlation_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('roads', sa.Column('geometry', sa.JSON(), nullable=True))
    op.drop_constraint(op.f('roads_end_intersection_id_fkey'), 'roads', type_='foreignkey')
    op.drop_constraint(op.f('roads_start_intersection_id_fkey'), 'roads', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('roads_start_intersection_id_fkey'), 'roads', 'intersections', ['start_intersection_id'], ['id'])
    op.create_foreign_key(op.f('roads_end_intersection_id_fkey'), 'roads', 'intersections', ['end_intersection_id'], ['id'])
    op.drop_column('roads', 'geometry')
    op.alter_column('events', 'correlation_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
