"""add citizen requests

Revision ID: 98e5ee425933
Revises: 7db9af1d5bc6
Create Date: 2026-10-08 22:16:38.437857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98e5ee425933'
down_revision: Union[str, Sequence[str], None] = '7db9af1d5bc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('citizen_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('correlation_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_citizen_requests_correlation_id', 'citizen_requests', ['correlation_id'], unique=False)
    op.create_index('ix_citizen_requests_created_at', 'citizen_requests', ['created_at'], unique=False)
    op.create_index('ix_citizen_requests_status', 'citizen_requests', ['status'], unique=False)
    op.alter_column('events', 'correlation_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'correlation_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index('ix_citizen_requests_status', table_name='citizen_requests')
    op.drop_index('ix_citizen_requests_created_at', table_name='citizen_requests')
    op.drop_index('ix_citizen_requests_correlation_id', table_name='citizen_requests')
    op.drop_table('citizen_requests')
    # ### end Alembic commands ###
