"""add roads and events

Revision ID: d14cd9f9e3cd
Revises: ab3aa38adaba
Create Date: 2026-10-05 22:15:14.535134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd14cd9f9e3cd'
down_revision: Union[str, Sequence[str], None] = 'ab3aa38adaba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('aggregate_id', sa.Uuid(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intersections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('traffic_light', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('road_type', sa.String(length=50), nullable=False),
    sa.Column('start_intersection_id', sa.Uuid(), nullable=False),
    sa.Column('end_intersection_id', sa.Uuid(), nullable=False),
    sa.Column('length_meters', sa.Float(), nullable=False),
    sa.Column('speed_limit_kmh', sa.Float(), nullable=False),
    sa.Column('lanes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['end_intersection_id'], ['intersections.id'], ),
    sa.ForeignKeyConstraint(['start_intersection_id'], ['intersections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roads')
    op.drop_table('intersections')
    op.drop_table('events')
    # ### end Alembic commands ###
