"""add event correlation id

Revision ID: f33b33de1a00
Revises: d14cd9f9e3cd
Create Date: 2026-10-06 11:46:51.711235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f33b33de1a00'
down_revision: Union[str, Sequence[str], None] = 'd14cd9f9e3cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('correlation_id', sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'correlation_id')
    # ### end Alembic commands ###
